FROM python3.6
WORKDIR /srv/costcontrol
RUN pip install pipenv
# RUN apt install -y \
#     postgresql-common \
#     postgresql-client \
#     libjpeg \
#     zlib \
#     libtiff \
#     libfreetype \
#     littlecms \
#     libwebp \
#     tcl/tk \
#     openjpeg \
#     libimagequant \
#     libraqm
