- name: Copy nginx config
  become: yes
  become_user: root
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"

- name: Reload nginx
  become: yes
  become_user: root
  service:
    name: nginx
    state: reloaded
