- hosts: all
  become: yes
  become_user: "{{ user }}"

  handlers:
  - name: reload-nginx
    become: yes
    become_user: root
    service:
      name: nginx
      state: reloaded

  tasks:
  - name: Fetch repo
    git:
      repo: https://github.com/yegorLitvinov/costcontrol.git
      dest: "{{ project_dir }}"

  - name: Copy docker-compose
    template:
      src: docker-compose.yml
      dest: "{{ project_dir }}"

  - name: Setup docker-compose services
    docker_service:
      project_name: "{{ project_name }}"
      project_src: "{{ project_dir }}"

  - name: Assert services running
    assert:
      that:
        - "postgres.{{ project_name }}_postgres_1.state.running"
        - "memcached.{{ project_name }}_memcached_1.state.running"
        - "web.{{ project_name }}_web_1.state.running"

  - name: Create database and user
    command: pipenv shell 'cd backend && python manage.py sqlcreate | psql -h postgres -U postgres'
  # - name: Apply migrations
  # - name: Build static

  - name: Remove default site
    become: yes
    become_user: root
    file:
      name: /etc/nginx/sites-enabled/default
      state: absent
    notify: reload-nginx

  - name: Copy nginx config
    become: yes
    become_user: root
    template:
      src: nginx.conf.j2
      dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    notify: reload-nginx

  # - name: Restart Gunicorn
