user: web
user_home: /home/web
project_name: costcontrol
project_dir: "{{ user_home }}/{{ project_name }}"
user_pass: "{{ lookup('env','USER_PASS') }}"

admin_email: "{{ lookup('env','ADMIN_EMAIL') }}"

# Private docker network base address
base_ip: "172.20.20"

web_domain: "{{ lookup('env','WEB_DOMAIN') }}"

cert_domains:
  - "{{ web_domain }}"

nginx_servers:
  - name: "{{ web_domain }}"
    host: "{{ base_ip }}.12"
    port: 8000
    static:
      - url: /media/
        path: "{{ project_dir }}/media/"
        directive: alias
      - url: /static/
        path: "{{ project_dir }}/static/"
        directive: alias
      - url: /assets/
        path: "{{ project_dir }}/frontend/dist/assets/"
        directive: alias
      - url: /
        path: "/frontend/dist/index.html break"
        directive: "rewrite ^"
