user: costcontrol
user_pass: "{{ lookup('env','USER_PASS') }}"
user_home: /home/costcontrol
project_name: costcontrol
project_dir: "{{ user_home }}/{{ project_name }}"

venv_dir: "{{ project_dir }}/.venv"
django_dir: "{{ project_dir }}/backend"
django_settings: config.settings.prod
gunicorn_host: localhost
gunicorn_port: 8000

repo: https://github.com/yegorLitvinov/costcontrol
web_domain: cc.tvgun.ga

nginx_servers:
  - name: "{{ web_domain }}"
    host: "{{ gunicorn_host }}"
    port: "{{ gunicorn_port }}"
    static:
      - url: /media/
        path: "{{ project_dir }}/media/"
        directive: alias
      - url: /static/
        path: "{{ project_dir }}/static/"
        directive: alias
      - url: /assets/
        path: "{{ project_dir }}/frontend/dist/assets/"
        directive: alias
      - url: /
        path: "/frontend/dist/index.html break"
        directive: "rewrite ^"
