- name: Install supervisor
  become: yes
  become_user: root
  apt:
    name: supervisor

- name: Copy supervisor config
  become: yes
  become_user: root
  template:
    src: supervisor.conf.j2
    dest: "/etc/supervisor/conf.d/{{ project_name }}.conf"
  notify:
    - restart-supervisor
