- name: Install nginx
  apt:
    name: "{{ item }}"
  with_items:
    - nginx

- name: Remove default site
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Create /etc/nginx/dhparams.pem
  copy:
    content: ""
    force: no
    dest: /etc/nginx/dhparams.pem
  notify:
    - generate-dhparam
